### ISSUE TITLE
Stargates

### ISSUE THREAD

**Issue by craig1988** [Nex4rius/Stargate-Programm#308]
Is so strange when I copy a save world all my gates are rest any idea why I have to go round them all again and rename each star gate

**Comment by Nex4rius** [comment]
Did the address of the gates change after copying?
Do you copy your world often?

**Comment by Nex4rius** [comment]
I just tested it and I can see no change after starting the copied world.

Are you maybe using a tool for copying?

**Comment by craig1988** [comment]
The last 2 digets of the addresses change ?

**Comment by craig1988** [comment]
No using surfacebook pro windows 10 just a sanded copyied file

**Comment by Nex4rius** [comment]
There was an change in sgcraft were all addresses changed the last 2 digits and of course my program cannot detect that.
You have to remove the old addresses and input the new and then spread that address list to all gates without having two computers talk to each other otherwise they will share the old addresses again.
The old and the new address are both valid and my program adds addresses automatically if they are different and valid.
I can't do anything. :(

**Comment by Nex4rius** [comment]
You could go into your save file into the opencomputers folder and to the individual hard drives and edit the address files there.

There are two address files because I wanted to change something but never finished it.
So you have to delete the file
>/einstellungen/adressen.lua

and edit
>/stargate/adressen.lua

for every hard drive in your world that has a computer and remove the old addresses and add the new ones.

If you forget one computer and you connect to it later with the stargate you will get all the "bad" addresses again.

**Comment by craig1988** [comment]
Would I just be better to
Go back to a pervious version of the mod lol

**Comment by Nex4rius** [comment]
I think that should work too.
All the new addresses shouldn't be valid which means my program ignores them and it will delete them when it adds a new address.

It just depends on weather you want to get sgcraft updates or not.

**Comment by craig1988** [comment]
Which version should I port back to ?

**Comment by Nex4rius** [comment]
>Version 1.13.0
    Updated for Minecraft 1.10.2.
    The addressing scheme for dimensions has changed. Dimension addresses are now assigned dynamically, so dimension numbers are no longer restricted to -648 to 647 (there is a limit of 1296 different dimensions containing gates, but that's very unlikely to be reached). Also, the dimension symbols are hashed with the rest of the address, so you can't easily tell which dimension a gate is in from its address. As a result of these changes, if you have converted a world from a previous version, the reported addresses of existing gates will have changed in the last two characters. You will still be able to dial them using the old addresses, however.
    Order of chevron engagement is now more authentic.
    Improved repositioning of chevrons in response to base camouflage.
    Accidental breaking of a connected gate is prevented in creative mode.
    Fixed: Crash on casting a fishing line through a gate. (Can't fish through the gate, though, sorry.)
    Fixed: Extra leash dropped when leashed entity passed through a gate.

Before 1.13.0 but you lose important stuff like
> Order of chevron engagement is now more authentic.

**Comment by craig1988** [comment]
So I should download the one just before 1.13.0

**Comment by craig1988** [comment]
Or I should down load 1.13.0

**Comment by Nex4rius** [comment]
1.13.0 is the one with the change so that wouldn't change anything.

**Comment by craig1988** [comment]
That's weird tho cause that's the first version for 1.10.2 and I have been able to copy saved files on 1.10.2 with out a problem this is something that only happens recently

**Comment by craig1988** [comment]
There must be another cause to it cause iv only ever played minecraft on 1.10..2

**Comment by craig1988** [comment]
And I used to be able to copy the files fine

**Comment by Nex4rius** [comment]
This
>The last 2 digets of the addresses change ?

sounds to me like
>As a result of these changes, if you have converted a world from a previous version, the reported addresses of existing gates will have changed in the last two characters.



But if there is no connection with the version then it's likely a problem with the mod itself.
Ask the mod developer <a href="https://github.com/gcewing/SGCraft/issues/new">here</a>.
