### ISSUE TITLE
[nexDHD] Iris doesn't close on incoming dial

### ISSUE THREAD

**Issue by Nyabloody** [Nex4rius/Stargate-Programm#449]
Version Infos:
Minecraft 1.12.2
nexDHD 3.1.5
SGCraft 2.0.3
OpenComputers 1.7.5.19

I configured the gate with an IDC and nexDHD doesn't close the iris on incoming dialing, leaving the gate open for any intruders... The 2nd gate isn't managed by a computer btw.

**Comment by Nyabloody** [comment]
Ok I can confirm it's a bug in nexDHD. The iris is auto closing when both gates are managed by nexDHD. Otherwise nexDHD does nothing when the other gate isn't managed by nexDHD. Can you fix it ? Thanks.

**Comment by Nex4rius** [comment]
I've just tested it and the iris is closing as expected when you are dialling from a gate without nexDHD.

I only found SGCraft 2.0.2 so maybe its different in 2.0.3 and I'm running OpenComputers 1.7.5.192 instead of 1.7.5.19.

Can you update Opencomputers and give me the link to the 2.0.3 sgcraft?
Have you tried to reinstall nexDHD on a new disk?

**Comment by Nyabloody** [comment]
Yeah sorry mistypo. I'm using OC 1.7.5.192 too.

And for SGCraft 2.0.3 it's on curseforge here https://www.curseforge.com/minecraft/mc-mods/stargate-network/files

I will try to install nexDHD on a new disk and try again.

**Comment by Nyabloody** [comment]
Fresh new save, tried to dial the stargate controlled by nexdhd with another one that is not controlled by nexdhd and it still makes the iris stay open for intruders.

**Comment by Nex4rius** [comment]
I can't replicate that.

Could you make a video showing it all? Maybe you made a mistake somewhere.

**Comment by Nyabloody** [comment]
Here is a video:
https://www.youtube.com/watch?v=wS9fRHqlyVE
